import logging
import pathlib

import jax.numpy as jnp
import numpy as np

from smefit.rge import RGE

current_file_path = pathlib.Path(__file__).resolve().parent

oo_ww_wc_basis = ["OpD", "OpWB", "OWWW", "Opl1", "Ope", "O3pl1"]

_logger = logging.getLogger(__name__)


def compute_rge_matrix(coefficients, rge_dict, scale):
    rge_runner = RGE(
        wc_names=coefficients.names,
        init_scale=rge_dict["init_scale"],
        accuracy=rge_dict.get("smeft_accuracy", "integrate"),
        adm_QCD=rge_dict.get("adm_QCD", False),
        yukawa=rge_dict.get("yukawa", "top"),
    )
    rge_df = rge_runner.RGEmatrix(scale)
    gen_operators = list(rge_df.index)
    _logger.info("The operators generated by the RGE are: %s", gen_operators)

    return rge_df.values, np.array(gen_operators)


class OptimalWW_LEP3_161:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            rgemat, coeff_names = compute_rge_matrix(
                coefficients, rge_dict, scale=161.0
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LEP3_ww_lepto_161": "invcov_LEP3_ww_leptonic_161.dat",
            "LEP3_ww_semilep_161": "invcov_LEP3_ww_semilep_161.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        # FCCee (161): 19200 ab-1
        # LEP3 (161): 5600 ab-1
        self.incov_tot *= 5600 / 19200

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWW_LEP3_240:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            rgemat, coeff_names = compute_rge_matrix(
                coefficients, rge_dict, scale=240.0
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LEP3_ww_lepto_240": "invcov_LEP3_ww_leptonic_240.dat",
            "LEP3_ww_semilep_240": "invcov_LEP3_ww_semilep_240.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        # rescale invcov_tot by luminosity ratio starting from FCCee
        # FCCee (240): 10800 ab-1
        # LEP3 (240): 2304 ab-1
        self.incov_tot *= 2304 / 10800

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)
