import logging
import pathlib

import jax.numpy as jnp
import numpy as np

from smefit.rge import RGE, load_precomputed_rge_matrix, load_rge_mats_from_scales

current_file_path = pathlib.Path(__file__).resolve().parent

oo_ww_wc_basis = ["OpD", "OpWB", "OWWW", "Opl1", "Ope", "O3pl1"]
oo_tt_wc_basis = ["OpQM", "Opt", "OtW", "OtZ", "OQl1M", "OQe", "Otl1", "Ote"]

_logger = logging.getLogger(__name__)


def compute_rge_matrix(coefficients, rge_dict, scale):
    coeff_list = list(coefficients.names)
    rge_runner = RGE.from_rge_dict(rge_dict, coeff_list)

    rge_cache = {}
    path_to_rge_mat = rge_dict.get("rg_matrix", False)
    if path_to_rge_mat:
        rge_cache = load_precomputed_rge_matrix(path_to_rge_mat, rge_runner.settings)
    rge_df = load_rge_mats_from_scales([scale], coeff_list, rge_runner, rge_cache)[0]
    gen_operators = list(rge_df.index)
    _logger.info("The operators generated by the RGE are: %s", gen_operators)

    return rge_df.values, np.array(gen_operators)


class OptimalWWLCF250:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=250.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_ww_lepto_250_neg80_neg30": "invcov_LCF_ww_leptonic_250_neg80_neg30.dat",
            "LCF_ww_lepto_250_neg80_pos30": "invcov_LCF_ww_leptonic_250_neg80_pos30.dat",
            "LCF_ww_lepto_250_pos80_neg30": "invcov_LCF_ww_leptonic_250_pos80_neg30.dat",
            "LCF_ww_lepto_250_pos80_pos30": "invcov_LCF_ww_leptonic_250_pos80_pos30.dat",
            "LCF_ww_semilep_250_neg80_neg30": "invcov_LCF_ww_semilep_250_neg80_neg30.dat",
            "LCF_ww_semilep_250_neg80_pos30": "invcov_LCF_ww_semilep_250_neg80_pos30.dat",
            "LCF_ww_semilep_250_pos80_neg30": "invcov_LCF_ww_semilep_250_pos80_neg30.dat",
            "LCF_ww_semilep_250_pos80_pos30": "invcov_LCF_ww_semilep_250_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWWLCF5004ab:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=500.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_ww_lepto_500_4ab_neg80_neg30": "invcov_LCF_ww_leptonic_500_4ab_neg80_neg30.dat",
            "LCF_ww_lepto_500_4ab_neg80_pos30": "invcov_LCF_ww_leptonic_500_4ab_neg80_pos30.dat",
            "LCF_ww_lepto_500_4ab_pos80_neg30": "invcov_LCF_ww_leptonic_500_4ab_pos80_neg30.dat",
            "LCF_ww_lepto_500_4ab_pos80_pos30": "invcov_LCF_ww_leptonic_500_4ab_pos80_pos30.dat",
            "LCF_ww_semilep_500_4ab_neg80_neg30": "invcov_LCF_ww_semilep_500_4ab_neg80_neg30.dat",
            "LCF_ww_semilep_500_4ab_neg80_pos30": "invcov_LCF_ww_semilep_500_4ab_neg80_pos30.dat",
            "LCF_ww_semilep_500_4ab_pos80_neg30": "invcov_LCF_ww_semilep_500_4ab_pos80_neg30.dat",
            "LCF_ww_semilep_500_4ab_pos80_pos30": "invcov_LCF_ww_semilep_500_4ab_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWWLCF5008ab:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=500.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_ww_lepto_500_8ab_neg80_neg30": "invcov_LCF_ww_leptonic_500_8ab_neg80_neg30.dat",
            "LCF_ww_lepto_500_8ab_neg80_pos30": "invcov_LCF_ww_leptonic_500_8ab_neg80_pos30.dat",
            "LCF_ww_lepto_500_8ab_pos80_neg30": "invcov_LCF_ww_leptonic_500_8ab_pos80_neg30.dat",
            "LCF_ww_lepto_500_8ab_pos80_pos30": "invcov_LCF_ww_leptonic_500_8ab_pos80_pos30.dat",
            "LCF_ww_semilep_500_8ab_neg80_neg30": "invcov_LCF_ww_semilep_500_8ab_neg80_neg30.dat",
            "LCF_ww_semilep_500_8ab_neg80_pos30": "invcov_LCF_ww_semilep_500_8ab_neg80_pos30.dat",
            "LCF_ww_semilep_500_8ab_pos80_neg30": "invcov_LCF_ww_semilep_500_8ab_pos80_neg30.dat",
            "LCF_ww_semilep_500_8ab_pos80_pos30": "invcov_LCF_ww_semilep_500_8ab_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWWLCF1000:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=1000.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_ww_lepto_1000_neg80_neg20": "invcov_LCF_ww_leptonic_1000_neg80_neg20.dat",
            "LCF_ww_lepto_1000_neg80_pos20": "invcov_LCF_ww_leptonic_1000_neg80_pos20.dat",
            "LCF_ww_lepto_1000_pos80_neg20": "invcov_LCF_ww_leptonic_1000_pos80_neg20.dat",
            "LCF_ww_lepto_1000_pos80_pos20": "invcov_LCF_ww_leptonic_1000_pos80_pos20.dat",
            "LCF_ww_semilep_1000_neg80_neg20": "invcov_LCF_ww_semilep_1000_neg80_neg20.dat",
            "LCF_ww_semilep_1000_neg80_pos20": "invcov_LCF_ww_semilep_1000_neg80_pos20.dat",
            "LCF_ww_semilep_1000_pos80_neg20": "invcov_LCF_ww_semilep_1000_pos80_neg20.dat",
            "LCF_ww_semilep_1000_pos80_pos20": "invcov_LCF_ww_semilep_1000_pos80_pos20.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalttLCF350:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=350.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_tt_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_tt_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_tt_wbwb_350_neg80_neg30": "invcov_LCF_tt_wbwb_350_neg80_neg30.dat",
            "LCF_tt_wbwb_350_pos80_neg30": "invcov_LCF_tt_wbwb_350_pos80_neg30.dat",
            "LCF_tt_wbwb_350_neg80_pos30": "invcov_LCF_tt_wbwb_350_neg80_pos30.dat",
            "LCF_tt_wbwb_350_pos80_pos30": "invcov_LCF_tt_wbwb_350_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_tt_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalttLCF5004ab:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=500.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_tt_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_tt_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_tt_wbwb_500_4ab_neg80_neg30": "invcov_LCF_tt_wbwb_500_4ab_neg80_neg30.dat",
            "LCF_tt_wbwb_500_4ab_pos80_neg30": "invcov_LCF_tt_wbwb_500_4ab_pos80_neg30.dat",
            "LCF_tt_wbwb_500_4ab_neg80_pos30": "invcov_LCF_tt_wbwb_500_4ab_neg80_pos30.dat",
            "LCF_tt_wbwb_500_4ab_pos80_pos30": "invcov_LCF_tt_wbwb_500_4ab_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_tt_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalttLCF5008ab:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=500.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_tt_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_tt_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_tt_wbwb_500_8ab_neg80_neg30": "invcov_LCF_tt_wbwb_500_8ab_neg80_neg30.dat",
            "LCF_tt_wbwb_500_8ab_pos80_neg30": "invcov_LCF_tt_wbwb_500_8ab_pos80_neg30.dat",
            "LCF_tt_wbwb_500_8ab_neg80_pos30": "invcov_LCF_tt_wbwb_500_8ab_neg80_pos30.dat",
            "LCF_tt_wbwb_500_8ab_pos80_pos30": "invcov_LCF_tt_wbwb_500_8ab_pos80_pos30.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_tt_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalttLCF1000:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=1000.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_tt_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_tt_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "LCF_tt_wbwb_1000_neg80_neg20": "invcov_LCF_tt_wbwb_1000_neg80_neg20.dat",
            "LCF_tt_wbwb_1000_pos80_neg20": "invcov_LCF_tt_wbwb_1000_pos80_neg20.dat",
            "LCF_tt_wbwb_1000_neg80_pos20": "invcov_LCF_tt_wbwb_1000_neg80_pos20.dat",
            "LCF_tt_wbwb_1000_pos80_pos20": "invcov_LCF_tt_wbwb_1000_pos80_pos20.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_tt_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)
