import logging
import pathlib

import jax.numpy as jnp
import numpy as np

from smefit.rge import RGE, read_rge_cache, resolve_rge_matrices

current_file_path = pathlib.Path(__file__).resolve().parent

oo_ww_wc_basis = ["OpD", "OpWB", "OWWW", "Opl1", "Ope", "O3pl1"]
oo_tt_wc_basis = ["OpQM", "Opt", "OtW", "OtZ", "OQl1M", "OQe", "Otl1", "Ote"]

_logger = logging.getLogger(__name__)


def compute_rge_matrix(coefficients, rge_dict, scale):
    coeff_list = list(coefficients.names)
    rge_runner = RGE.from_rge_dict(rge_dict, coeff_list)

    rge_cache = {}
    path_to_rge_mat = rge_dict.get("rg_matrix", False)
    if path_to_rge_mat:
        rge_cache = read_rge_cache(path_to_rge_mat, rge_runner.settings)
    rge_df = resolve_rge_matrices([scale], coeff_list, rge_runner, rge_cache)[0]
    gen_operators = list(rge_df.index)
    _logger.info("The operators generated by the RGE are: %s", gen_operators)

    return rge_df.values, np.array(gen_operators)


class OptimalWWCEPC161:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=161.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "CEPC_ww_lepto_161": "invcov_CEPC_ww_leptonic_161.dat",
            "CEPC_ww_semilep_161": "invcov_CEPC_ww_semilep_161.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWWCEPC240:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=240.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "CEPC_ww_lepto_240": "invcov_CEPC_ww_leptonic_240.dat",
            "CEPC_ww_semilep_240": "invcov_CEPC_ww_semilep_240.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalWWCEPC365:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=365.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_ww_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_ww_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {
            "CEPC_ww_lepto_365": "invcov_CEPC_ww_leptonic_365.dat",
            "CEPC_ww_semilep_365": "invcov_CEPC_ww_semilep_365.dat",
        }

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_ww_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)


class OptimalttCEPC365:
    def __init__(self, coefficients, rge_dict=None):
        if rge_dict is not None:
            _obs_scale = rge_dict.get("obs_scale", "dynamic")
            rgemat, coeff_names = compute_rge_matrix(
                coefficients,
                rge_dict,
                scale=365.0 if _obs_scale == "dynamic" else _obs_scale,
            )
        else:
            rgemat = None
            coeff_names = np.array(coefficients.names)

        self.project = np.zeros((len(oo_tt_wc_basis), len(coeff_names)))
        for i, op in enumerate(oo_tt_wc_basis):
            if op in coeff_names:
                self.project[i, np.argwhere(coeff_names == op)[0, 0]] = 1

        self.datasets = {"CEPC_tt_365": "invcov_CEPC_tt_365GeV.dat"}

        incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path)
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)

        self.rgemat = rgemat

        if self.rgemat is not None:
            # multiply the RGE matrix as well
            self.incov_tot = jnp.einsum(
                "ij, jk, kl", self.rgemat.T, self.incov_tot, self.rgemat
            )

        self.coefficients = coefficients
        self.num_data = len(oo_tt_wc_basis)

    def compute_chi2(self, coefficient_values):
        resolved = self.coefficients.resolve(coefficient_values)
        return jnp.einsum("i, ij, j", resolved, self.incov_tot, resolved)
