#!/usr/bin/env python
"""Generate the auto-generated reference files bundled with the Claude Code skills.

Introspects the smefit package (runcard keys from smefit.config, actions from the
provider modules registered in smefit.app, prior distributions from smefit.priors)
and copies the template runcards, writing the results into the skill directories
under .claude/skills/.

Usage:
    python scripts/generate_skill_reference.py           # regenerate in place
    python scripts/generate_skill_reference.py --check   # exit 1 if committed files are stale

Run from an environment where smefit is installed (e.g. `conda activate new_smefit`).
CI runs the --check mode so these files cannot drift from the code.
"""

import argparse
import ast
import difflib
import importlib
import inspect
import json
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_skill_reference.py — do not edit.\n"
    "     Regenerate with: python scripts/generate_skill_reference.py -->\n\n"
)
TEMPLATE_BANNER = (
    "# AUTO-COPIED from template_runcards/{name} by scripts/generate_skill_reference.py\n"
    "# — edit the original and regenerate; do not edit this copy.\n"
    "#\n"
    "# These are the repo's smoke-test runcards, so the settings blocks and the\n"
    "# overall shape are authoritative, but the PHYSICS CONTENT is placeholder:\n"
    "# the `datasets`, `coefficients` (especially any `expr` constraints) and\n"
    "# `external_chi2` entries are illustrative and must be replaced with ones\n"
    "# chosen for the analysis at hand — do not carry them over verbatim.\n"
)

# Runcard keys consumed by reportengine itself rather than smefitConfig.
REPORTENGINE_KEYS = {
    "actions_": "List of actions to execute (see actions.md). Required in every runcard.",
    "template_text": "Inline reportengine report template with {@action@} tags (used with the `report` action).",
    "meta": "Optional metadata block (title, author, keywords) used by reportengine reports.",
}

# Raw params that look like runcard keys but are internal reportengine namespace
# entries (produced via NSList nskey), never written by users.
IGNORED_RAW_PARAMS = {"individual_fit_coefficient"}

# Runnable actions vs internal providers. reportengine will happily accept any
# provider under `actions_:`, but only these are meaningful entry points; the
# rest are intermediate nodes it resolves on demand.
ACTION_NAME_PREFIXES = ("run_", "write_", "plot_")
# Modules whose public functions are all report-tag actions (tables, figures).
ACTION_MODULES = {"smefit.tables", "smefit.figures"}
# Actions that follow neither rule.
EXTRA_ACTION_NAMES = {"chi2_timing", "time_chi2_vec"}


def is_runnable_action(module_name, func_name):
    """True if `func_name` is a legitimate `actions_:` entry."""
    return (
        module_name in ACTION_MODULES
        or func_name.startswith(ACTION_NAME_PREFIXES)
        or func_name in EXTRA_ACTION_NAMES
    )


# Curated map: fit type -> (action, settings blocks it reads). The action table
# itself is fully auto-generated; this map only adds the pairing guidance.
FIT_TYPE_MAP = [
    (
        "Analytic (linear/Gaussian posterior)",
        "run_analytic_fit",
        "none (optional n_samples/seed via analytic_fit defaults)",
    ),
    ("UltraNest nested sampling", "run_ultranest_fit", "ultranest_settings"),
    ("BlackJAX nested sampling", "run_blackjax_fit", "blackjax_settings"),
    (
        "Hessian / Laplace approximation",
        "run_hessian_fit",
        "optimizer_settings, gradient_descent_settings, hessian_settings",
    ),
    (
        "Individual (one free coefficient at a time)",
        "run_individual_<analytic|ultranest|blackjax|hessian>_fits",
        "same blocks as the joint variant",
    ),
    ("Pseudodata / projections", "write_pseudodata", "pseudodata_settings"),
    ("Likelihood timing benchmark", "chi2_timing", "none"),
    (
        "Report (Fisher information, tables, plots)",
        "report",
        "template_text + optimizer_settings/gradient_descent_settings (Fisher needs gd_best_fit)",
    ),
]


# --------------------------------------------------------------------------
# AST helpers for smefit/config.py
# --------------------------------------------------------------------------


def _method_asts(config_source):
    """Map method name -> ast.FunctionDef for smefitConfig."""
    tree = ast.parse(config_source)
    methods = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "smefitConfig":
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    methods[item.name] = item
    return methods


def _extract_known_keys(fn_ast):
    """Extract the `known_keys = {...}` set literal, if present."""
    for node in ast.walk(fn_ast):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Set):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
            if "known_keys" in targets:
                keys = [
                    el.value
                    for el in node.value.elts
                    if isinstance(el, ast.Constant) and isinstance(el.value, str)
                ]
                return sorted(keys)
    return None


def _extract_get_defaults(fn_ast):
    """Extract every `<obj>.get("key", default)` call -> {key: default_repr}."""
    defaults = {}
    for node in ast.walk(fn_ast):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ):
            key = node.args[0].value
            if len(node.args) > 1:
                defaults[key] = ast.unparse(node.args[1])
            else:
                defaults.setdefault(key, "(no default)")
    return defaults


def _extract_dict_defaults(fn_ast):
    """Extract `name = {literal dict}` assignments (e.g. reactive_defaults)."""
    found = {}
    for node in ast.walk(fn_ast):
        if (
            isinstance(node, ast.Assign)
            and isinstance(node.value, ast.Dict)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
        ):
            name = node.targets[0].id
            if name.endswith("_defaults"):
                found[name] = ast.unparse(node.value)
    return found


def _extract_error_constraints(fn_ast):
    """Collect string messages from `raise ConfigError(...)` / ValueError / FileNotFoundError."""
    messages = []
    for node in ast.walk(fn_ast):
        if isinstance(node, ast.Raise) and isinstance(node.exc, ast.Call):
            func = node.exc.func
            name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", "")
            if name in {"ConfigError", "ValueError", "FileNotFoundError"}:
                strings = [
                    a.value
                    for a in node.exc.args
                    if isinstance(a, ast.Constant) and isinstance(a.value, str)
                ]
                msg = " ".join(s for s in strings if len(s) > 15)
                if msg:
                    messages.append(msg)
    return sorted(set(messages))


# --------------------------------------------------------------------------
# Config surface collection
# --------------------------------------------------------------------------


def collect_config_surface():
    """Introspect smefitConfig: parse_* keys, produce_* nodes, raw runcard keys."""
    from smefit.config import smefitConfig

    config_source = inspect.getsource(sys.modules["smefit.config"])
    method_asts = _method_asts(config_source)

    parse_entries = []
    produce_entries = []
    parse_keys, produce_keys = set(), set()

    for name in sorted(dir(smefitConfig)):
        if not (name.startswith("parse_") or name.startswith("produce_")):
            continue
        method = getattr(smefitConfig, name)
        if not callable(method) or name not in method_asts:
            continue  # inherited reportengine machinery is not smefit surface
        doc = inspect.getdoc(method) or ""
        fn_ast = method_asts[name]
        entry = {
            "key": name.split("_", 1)[1],
            "doc": doc,
            "known_keys": _extract_known_keys(fn_ast),
            "defaults": _extract_get_defaults(fn_ast),
            "dict_defaults": _extract_dict_defaults(fn_ast),
            "constraints": _extract_error_constraints(fn_ast),
        }
        if name.startswith("parse_"):
            parse_entries.append(entry)
            parse_keys.add(entry["key"])
        else:
            sig = inspect.signature(method)
            entry["params"] = [
                (
                    p.name,
                    None if p.default is inspect.Parameter.empty else repr(p.default),
                )
                for p in sig.parameters.values()
                if p.name != "self"
            ]
            produce_entries.append(entry)
            produce_keys.add(entry["key"])

    # Raw runcard keys: produce_* parameters that are neither parsed nor produced
    # resources — reportengine feeds them straight from the runcard.
    special = {"output_path"} | IGNORED_RAW_PARAMS
    raw_keys = {}
    for entry in produce_entries:
        for pname, pdefault in entry["params"]:
            if pname in parse_keys or pname in produce_keys or pname in special:
                continue
            raw_keys.setdefault(pname, {"default": pdefault, "used_by": []})
            raw_keys[pname]["used_by"].append(entry["key"])

    return {
        "parse": parse_entries,
        "produce": produce_entries,
        "raw": {k: raw_keys[k] for k in sorted(raw_keys)},
    }


def collect_actions():
    """Enumerate public functions of every provider module in smefit.app."""
    from smefit.app import smefit_providers

    modules = []
    for mod_name in smefit_providers:
        if mod_name == "reportengine.report":
            continue  # documented by hand below
        module = importlib.import_module(mod_name)
        funcs = []
        for fname in sorted(vars(module)):
            obj = vars(module)[fname]
            if (
                inspect.isfunction(obj)
                and obj.__module__ == mod_name
                and not fname.startswith("_")
            ):
                doc = (inspect.getdoc(obj) or "").split("\n\n")[0].replace("\n", " ")
                sig = inspect.signature(obj)
                funcs.append(
                    {
                        "name": fname,
                        "signature": str(sig),
                        "doc": doc,
                        "optional_params": [
                            p.name
                            for p in sig.parameters.values()
                            if p.default is not inspect.Parameter.empty
                        ],
                    }
                )
        if funcs:
            modules.append({"module": mod_name, "functions": funcs})
    return modules


def collect_coefficient_keys():
    """Introspect smefit.core.Coefficient: the sub-keys of a `coefficients:` entry.

    produce_coefficients builds these dataclasses straight from the runcard, so
    its fields (minus `name`, which is the mapping key) are exactly the allowed
    sub-keys — including ones no parser mentions, e.g. baseline_value.
    """
    import dataclasses

    from smefit.core import Coefficient

    fields = []
    for field in dataclasses.fields(Coefficient):
        if field.name == "name":
            continue  # supplied by the coefficients mapping key, not written
        if field.default is dataclasses.MISSING:
            default = None
        else:
            default = repr(field.default)
        fields.append({"name": field.name, "default": default})
    return fields


def collect_paths():
    """Introspect smefit.paths: prefix-resolution mechanism for runcard paths."""
    import smefit.paths as paths_mod

    return {
        "doc": (paths_mod.__doc__ or "").strip(),
        "standard_prefixes": sorted(paths_mod._STANDARD_PREFIXES),
        # Store repo-relative so the generated output is machine-independent.
        "config_file": str(
            paths_mod.USER_PATHS_CONFIG.relative_to(
                paths_mod.USER_PATHS_CONFIG.parents[1]
            )
        ),
    }


def collect_priors():
    """Enumerate prior distributions from smefit.priors._DIST_REGISTRY."""
    from smefit.priors import _DIST_REGISTRY

    priors = {}
    for dist_name in sorted(_DIST_REGISTRY):
        cls = _DIST_REGISTRY[dist_name]
        params = [
            p.name
            for p in inspect.signature(cls.__init__).parameters.values()
            if p.name != "self"
        ]
        priors[dist_name] = params
    return priors


# --------------------------------------------------------------------------
# Markdown rendering
# --------------------------------------------------------------------------


def _render_settings_block(entry):
    lines = [f"### `{entry['key']}`", ""]
    if entry["doc"]:
        lines += [entry["doc"], ""]
    if entry["known_keys"]:
        lines += ["Recognized sub-keys (unknown sub-keys only produce a warning):", ""]
        for k in entry["known_keys"]:
            default = entry["defaults"].get(k)
            if default is not None:
                lines.append(f"- `{k}` — default: `{default}`")
            else:
                lines.append(f"- `{k}`")
        lines.append("")
        extra = sorted(set(entry["defaults"]) - set(entry["known_keys"]))
    else:
        extra = sorted(entry["defaults"])
    extra = [k for k in extra if entry["defaults"][k] != "(no default)"]
    if extra:
        lines += ["Additional defaults applied while parsing:", ""]
        lines += [f"- `{k}` — default: `{entry['defaults'][k]}`" for k in extra]
        lines.append("")
    # Plain fence (not ```python): blacken-docs must not reformat generated output.
    for name, value in sorted(entry["dict_defaults"].items()):
        lines += [
            f"Internal defaults `{name}`:",
            "",
            f"```\n{name} = {value}\n```",
            "",
        ]
    if entry["constraints"]:
        lines += ["Validation errors raised while parsing:", ""]
        lines += [f"- {m}" for m in entry["constraints"]]
        lines.append("")
    return lines


def _render_coefficient_keys(coeff_keys):
    """Sub-key table for one `coefficients:` entry (from the Coefficient dataclass)."""
    lines = [
        "Each entry under `coefficients:` is `Name: {…}`. Allowed sub-keys, from",
        "the fields of `smefit.core.Coefficient` — anything else is ignored:",
        "",
        "| sub-key | default |",
        "|---|---|",
    ]
    for field in coeff_keys:
        default = (
            f"`{field['default']}`" if field["default"] is not None else "required"
        )
        lines.append(f"| `{field['name']}` | {default} |")
    lines += [
        "",
        "Which combination is legal depends on the coefficient kind (free / fixed /",
        "expression-constrained) — the invariants are enforced in",
        "`Coefficient.__post_init__` and spelled out in `coefficients.md`.",
        "",
    ]
    return lines


def render_runcard_keys_md(surface, paths_info, coeff_keys):
    lines = [
        BANNER.rstrip("\n"),
        "",
        "# smefit runcard key reference",
        "",
        "Only the keys documented here exist. smefit warns on unknown sub-keys instead",
        "of rejecting them, so a misspelled key is silently ignored — always validate",
        "with `scripts/validate_runcard.py`.",
        "",
        "## Path resolution (shareable runcards)",
        "",
        "Runcard paths (`data_path`, `theory_path`, `external_chi2[*].path`,",
        "`external_chi2[*].rg_matrix`, `rge.rg_matrix`) support prefix-relative form,",
        f"resolved via the machine-specific `{paths_info['config_file']}` (created by",
        "`smefit_setup_local`). Standard prefixes: "
        + ", ".join(f"`{p}`" for p in paths_info["standard_prefixes"])
        + ".",
        "From `smefit.paths`:",
        "",
        "```",
        paths_info["doc"],
        "```",
        "",
        "## Keys consumed directly from the runcard (no dedicated parser)",
        "",
    ]
    for key, info in surface["raw"].items():
        default = (
            f" — default: `{info['default']}`" if info["default"] is not None else ""
        )
        used_by = ", ".join(f"`{u}`" for u in sorted(set(info["used_by"])))
        lines.append(f"- `{key}`{default} (consumed by {used_by})")
    lines += [
        "",
        "Notes:",
        "",
        "- `datasets` is a list of entries `{name, order, theory_cov (optional, default",
        "  'current'), group (optional, for report/Fisher aggregation)}`.",
        "",
        "## reportengine keys",
        "",
    ]
    for key in sorted(REPORTENGINE_KEYS):
        lines.append(f"- `{key}` — {REPORTENGINE_KEYS[key]}")
    lines += ["", "## Keys with dedicated parsers", ""]
    for entry in surface["parse"]:
        lines += _render_settings_block(entry)
        if entry["key"] == "coefficients":
            lines += _render_coefficient_keys(coeff_keys)
    lines += [
        "## Derived resources (produced internally — NEVER write these in a runcard)",
        "",
        "reportengine builds these nodes on demand; they are listed so you can trace",
        "which runcard keys each action ultimately needs.",
        "",
    ]
    for entry in surface["produce"]:
        params = ", ".join(p for p, _ in entry["params"])
        doc = entry["doc"].split("\n")[0] if entry["doc"] else ""
        lines.append(f"- `{entry['key']}`({params}) — {doc}")
    lines.append("")
    return "\n".join(lines)


def _render_function_list(action_modules, runnable):
    """Render the per-module bullet lists, keeping only one side of the split."""
    lines = []
    for mod in action_modules:
        selected = [
            fn
            for fn in mod["functions"]
            if is_runnable_action(mod["module"], fn["name"]) is runnable
        ]
        if not selected:
            continue
        lines += [f"### `{mod['module']}`", ""]
        for fn in selected:
            lines.append(f"- `{fn['name']}{fn['signature']}`")
            if fn["doc"]:
                lines.append(f"  - {fn['doc']}")
        lines.append("")
    return lines


def render_actions_md(action_modules):
    lines = [
        BANNER.rstrip("\n"),
        "",
        "# smefit actions reference",
        "",
        "Provider functions come in two kinds, and the difference matters:",
        "",
        "- **Actions** (first list) are the entry points you write under `actions_:`",
        "  in a runcard, or call via `{@action@}` tags in a report `template_text`.",
        "- **Internal providers** (second list) are intermediate nodes reportengine",
        "  builds on demand to satisfy an action's arguments. Writing one of these",
        "  under `actions_:` is a mistake — it either fails or silently produces",
        "  nothing useful.",
        "",
        "Function arguments are config resources resolved automatically by",
        "reportengine (see runcard-keys.md for what each resource needs).",
        "",
        "## Which action for which fit",
        "",
        "| Fit type | Action | Settings blocks read |",
        "|---|---|---|",
    ]
    for fit_type, action, blocks in FIT_TYPE_MAP:
        lines.append(f"| {fit_type} | `{action}` | {blocks} |")
    lines += ["", "## Actions — valid under `actions_:`", ""]
    lines += _render_function_list(action_modules, runnable=True)
    lines += [
        "### `reportengine.report`",
        "",
        "- `report(...)` — renders `template_text` (or a `template` file), executing",
        "  every `{@action@}` tag and assembling an HTML report in the output folder.",
        "",
        "## Internal providers — NEVER write these under `actions_:`",
        "",
        "Listed so you can trace what an action depends on, and recognize these",
        "names in tracebacks. They are resolved for you.",
        "",
    ]
    lines += _render_function_list(action_modules, runnable=False)
    return "\n".join(lines)


def render_priors_md(priors):
    lines = [
        BANNER.rstrip("\n"),
        "",
        "# Prior distributions",
        "",
        "Allowed values of `dist` in a free coefficient's `prior:` block, with their",
        "required parameters. No other distributions exist.",
        "",
        "| dist | parameters | example |",
        "|---|---|---|",
    ]
    examples = {
        "uniform": "`{dist: uniform, low: -1.0, high: 1.0}`",
        "gaussian": "`{dist: gaussian, mean: 0.0, std: 1.0}`",
        "normal": "`{dist: normal, mean: 0.0, std: 1.0}` (alias of gaussian)",
    }
    for name, params in priors.items():
        example = examples.get(name, "")
        lines.append(
            f"| `{name}` | {', '.join(f'`{p}`' for p in params)} | {example} |"
        )
    lines += [
        "",
        "Special cases (selected automatically, never via `dist`):",
        "",
        "- `whitening:` block — every free coefficient gets `uniform[-sigma_prior, sigma_prior]`",
        "  in whitened space.",
        "- `bayesian_update_path:` — the previous fit's exact posterior becomes the prior.",
        "",
    ]
    return "\n".join(lines)


def collect_provider_arg_keys(action_modules, surface):
    """Optional provider-function arguments (e.g. n_samples, batch_sample_sizes).

    reportengine resolves action arguments from the config namespace, so any
    defaulted parameter of a provider function is a legitimate top-level
    runcard key. Resource names (parsed/produced) are excluded.
    """
    resources = (
        {e["key"] for e in surface["parse"]}
        | {e["key"] for e in surface["produce"]}
        | set(surface["raw"])
        | {"output_path"}
        | IGNORED_RAW_PARAMS
    )
    keys = set()
    for mod in action_modules:
        for fn in mod["functions"]:
            keys.update(fn["optional_params"])
    return sorted(keys - resources)


def build_runcard_keys_json(surface, priors, paths_info, action_modules, coeff_keys):
    """Machine-readable key list consumed by validate_runcard.py."""
    settings_blocks = {}
    for entry in surface["parse"]:
        settings_blocks[entry["key"]] = {
            "known_keys": entry["known_keys"],
            "defaults": entry["defaults"],
        }
    provider_args = collect_provider_arg_keys(action_modules, surface)
    top_level = sorted(
        set(surface["raw"])
        | set(settings_blocks)
        | set(REPORTENGINE_KEYS)
        | set(provider_args)
    )
    return {
        "top_level_keys": top_level,
        "settings_blocks": settings_blocks,
        "raw_keys": surface["raw"],
        "derived_keys": sorted(e["key"] for e in surface["produce"]),
        "prior_dists": priors,
        "coefficient_keys": [f["name"] for f in coeff_keys],
        "dataset_entry_keys": ["name", "order", "theory_cov", "group"],
        "path_prefixes": paths_info["standard_prefixes"],
        "paths_config": paths_info["config_file"],
        "provider_arg_keys": provider_args,
    }


def render_templates():
    """Copy template_runcards/*.yaml verbatim (plus banner).

    Templates already carry shareable prefix paths (smefit_database/commondata,
    new_smefit/external_chi2/...) resolved via .config/paths.yaml at run time,
    so no rewriting is needed.
    """
    out = {}
    template_dir = REPO_ROOT / "template_runcards"
    for path in sorted(template_dir.glob("*.yaml")):
        out[path.name] = TEMPLATE_BANNER.format(name=path.name) + path.read_text()
    return out


# --------------------------------------------------------------------------
# Output assembly
# --------------------------------------------------------------------------


def generate_outputs():
    """Return {relative posix path under .claude/skills: content}."""
    surface = collect_config_surface()
    action_modules = collect_actions()
    priors = collect_priors()
    paths_info = collect_paths()
    coeff_keys = collect_coefficient_keys()

    actions_md = render_actions_md(action_modules)
    outputs = {
        "smefit-runcard/references/runcard-keys.md": render_runcard_keys_md(
            surface, paths_info, coeff_keys
        ),
        "smefit-runcard/references/runcard-keys.json": json.dumps(
            build_runcard_keys_json(
                surface, priors, paths_info, action_modules, coeff_keys
            ),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        "smefit-runcard/references/actions.md": actions_md,
        "smefit-runcard/references/priors.md": render_priors_md(priors),
        "smefit-analysis/references/actions.md": actions_md,
    }
    for name, content in render_templates().items():
        outputs[f"smefit-runcard/templates/{name}"] = content
    return outputs


def write_outputs(outputs, skills_root):
    for rel, content in outputs.items():
        target = skills_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)


def check_outputs(outputs, skills_root):
    """Compare generated content against committed files. Return list of problems."""
    problems = []
    for rel, content in outputs.items():
        target = skills_root / rel
        if not target.exists():
            problems.append(f"MISSING: .claude/skills/{rel}")
            continue
        committed = target.read_text()
        if committed != content:
            diff = "".join(
                difflib.unified_diff(
                    committed.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"committed/{rel}",
                    tofile=f"generated/{rel}",
                )
            )
            problems.append(
                f"STALE: .claude/skills/{rel}\n{textwrap.indent(diff, '    ')}"
            )
    # The templates dir is fully generator-owned: flag stray files.
    templates_dir = skills_root / "smefit-runcard" / "templates"
    if templates_dir.exists():
        expected = {
            Path(rel).name
            for rel in outputs
            if rel.startswith("smefit-runcard/templates/")
        }
        for path in sorted(templates_dir.glob("*.yaml")):
            if path.name not in expected:
                problems.append(
                    f"ORPHAN: .claude/skills/smefit-runcard/templates/{path.name} "
                    "(no matching file in template_runcards/)"
                )
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the committed files differ from regenerated output.",
    )
    args = parser.parse_args()

    skills_root = REPO_ROOT / ".claude" / "skills"
    outputs = generate_outputs()

    if args.check:
        problems = check_outputs(outputs, skills_root)
        if problems:
            print("Skill reference files are out of date with the code:\n")
            print("\n".join(problems))
            print(
                "\nFix: run `python scripts/generate_skill_reference.py` and commit "
                "the updated files."
            )
            return 1
        print(f"Skill reference files are up to date ({len(outputs)} files checked).")
        return 0

    write_outputs(outputs, skills_root)
    print(f"Wrote {len(outputs)} files under {skills_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
