from matplotlib import rc

rc("font", **{"family": "sans-serif", "sans-serif": ["Helvetica"], "size": 22})
rc("text", usetex=True)
rc("text.latex", preamble=r"\usepackage{amssymb}")

coeff_info_latex = {
    # --------------------------
    # 4H sector
    # --------------------------
    "OQQ1": r"$c_{QQ}^{\scriptscriptstyle 1}$",
    "OQQ8": r"$c_{QQ}^{\scriptscriptstyle 8}$",
    "OQt1": r"$c_{Qt}^{\scriptscriptstyle 1}$",
    "OQt8": r"$c_{Qt}^{\scriptscriptstyle 8}$",
    "OQb1": r"$c_{Qb}^{\scriptscriptstyle 1}$",
    "OQb8": r"$c_{Qb}^{\scriptscriptstyle 8}$",
    "Ott1": r"$c_{tt}^{\scriptscriptstyle 1}$",
    "Obb": r"$c_{bb}$",
    "Otb1": r"$c_{tb}^{\scriptscriptstyle 1}$",
    "Otb8": r"$c_{tb}^{\scriptscriptstyle 8}$",
    "OQtQb1": r"$c_{QtQb}^{\scriptscriptstyle 1}$",
    "OQtQb8": r"$c_{QtQb}^{\scriptscriptstyle 8}$",
    # --------------------------
    # 2L2H sector
    # --------------------------
    "O81qq": r"$c_{Qq}^{\scriptscriptstyle 1,8}$",
    "O11qq": r"$c_{Qq}^{\scriptscriptstyle 1,1}$",
    "O83qq": r"$c_{Qq}^{\scriptscriptstyle 3,8}$",
    "O13qq": r"$c_{Qq}^{\scriptscriptstyle 3,1}$",
    "O8qt": r"$c_{tq}^{\scriptscriptstyle 8}$",
    "O1qt": r"$c_{tq}^{\scriptscriptstyle 1}$",
    "O8ut": r"$c_{tu}^{\scriptscriptstyle 8}$",
    "O1ut": r"$c_{tu}^{\scriptscriptstyle 1}$",
    "O8qu": r"$c_{Qu}^{\scriptscriptstyle 8}$",
    "O1qu": r"$c_{Qu}^{\scriptscriptstyle 1}$",
    "O8dt": r"$c_{td}^{\scriptscriptstyle 8}$",
    "O1dt": r"$c_{td}^{\scriptscriptstyle 1}$",
    "O8qd": r"$c_{Qd}^{\scriptscriptstyle 8}$",
    "O1qd": r"$c_{Qd}^{\scriptscriptstyle 1}$",
    # --------------------------
    # 2FB sector
    # --------------------------
    "Ocp": r"$c_{c\varphi}$",
    "Obp": r"$c_{b\varphi}$",
    "Otp": r"$c_{t\varphi}$",
    "Otap": r"$c_{\tau\varphi}$",
    "OtG": r"$c_{tG}$",
    "Omup": r"$c_{\mu\varphi}$",
    "OtW": r"$c_{tW}$",
    "OtZ": r"$c_{tZ}$",
    "OtB": r"$c_{tB}$",
    "ObW": r"$c_{bW}$",
    "O3pq": r"$c_{\varphi q}^{\scriptscriptstyle (3)}$",
    "O3pQ3": r"$c_{\varphi Q}^{\scriptscriptstyle (3)}$",
    "OpqMi": r"$c_{\varphi q}^{\scriptscriptstyle (-)}$",
    "OpQM": r"$c_{\varphi Q}^{\scriptscriptstyle (-)}$",
    "Opqi": r"$c_{\varphi q}^{\scriptscriptstyle (1)}$",
    "OpQ": r"$c_{\varphi Q}^{\scriptscriptstyle (1)}$",
    "Opui": r"$c_{\varphi u}$",
    "Opdi": r"$c_{\varphi d}$",
    "Opt": r"$c_{\varphi t}$",
    "Optb": r"$c_{\varphi tb}$",
    "Opl1": r"$c_{\varphi l_1}$",
    "Opl2": r"$c_{\varphi l_2}$",
    "Opl3": r"$c_{\varphi l_3}$",
    "Opl": r"$c_{\varphi l}$",
    "O3pl1": r"$c_{\varphi l_1}^{\scriptscriptstyle (3)}$",
    "O3pl2": r"$c_{\varphi l_2}^{\scriptscriptstyle (3)}$",
    "O3pl3": r"$c_{\varphi l_3}^{\scriptscriptstyle (3)}$",
    "O3pl": r"$c_{\varphi l}^{\scriptscriptstyle (3)}$",
    "Ope": r"$c_{\varphi e}$",
    "Opmu": r"$c_{\varphi \mu}$",
    "Opta": r"$c_{\varphi \tau}$",
    # --------------------------
    # 4l sector
    # --------------------------
    "Oll1221": r"$c_{ll}^{\scriptscriptstyle 1221}$",
    "Oll1111": r"$c_{ll}^{\scriptscriptstyle 1111}$",
    "Oll2222": r"$c_{ll}^{\scriptscriptstyle 2222}$",
    "Oll2233": r"$c_{ll}^{\scriptscriptstyle 2233}$",
    "Oll3333": r"$c_{ll}^{\scriptscriptstyle 3333}$",
    "Oll1122": r"$c_{ll}^{\scriptscriptstyle 1122}$",
    "Oll1133": r"$c_{ll}^{\scriptscriptstyle 1133}$",
    "Oll1331": r"$c_{ll}^{\scriptscriptstyle 1331}$",
    "Oll2332": r"$c_{ll}^{\scriptscriptstyle 2332}$",
    "Ole1111": r"$c_{le}^{\scriptscriptstyle 1111}$",
    "Ole2222": r"$c_{le}^{\scriptscriptstyle 2222}$",
    "Ole2233": r"$c_{le}^{\scriptscriptstyle 2233}$",
    "Ole3322": r"$c_{le}^{\scriptscriptstyle 3322}$",
    "Ole3333": r"$c_{le}^{\scriptscriptstyle 3333}$",
    "Ole1122": r"$c_{le}^{\scriptscriptstyle 1122}$",
    "Ole1133": r"$c_{le}^{\scriptscriptstyle 1133}$",
    "Ole2211": r"$c_{le}^{\scriptscriptstyle 2211}$",
    "Ole3311": r"$c_{le}^{\scriptscriptstyle 3311}$",
    "Oee1111": r"$c_{ee}^{\scriptscriptstyle 1111}$",
    "Oee2222": r"$c_{ee}^{\scriptscriptstyle 2222}$",
    "Oee2233": r"$c_{ee}^{\scriptscriptstyle 2233}$",
    "Oee3333": r"$c_{ee}^{\scriptscriptstyle 3333}$",
    "Oee1122": r"$c_{ee}^{\scriptscriptstyle 1122}$",
    "Oee1133": r"$c_{ee}^{\scriptscriptstyle 1133}$",
    "Oee": r"$c_{ee}$",
    "Oll": r"$c_{ll}$",
    "Ollprime": r"$c_{ll}^\prime$",
    "Ole": r"$c_{le}$",
    # --------------------------
    # B sector
    # --------------------------
    "OpG": r"$c_{\varphi G}$",
    "OpGtil": r"$c_{\widetilde{\varphi G}}$",
    "OpB": r"$c_{\varphi B}$",
    "OpBtil": r"$c_{\widetilde{\varphi B}}$",
    "OpW": r"$c_{\varphi W}$",
    "OpWtil": r"$c_{\widetilde{\varphi W}}$",
    "OpWB": r"$c_{\varphi WB}$",
    "OpWBtil": r"$c_{\widetilde{\varphi WB}}$",
    "OWWW": r"$c_{WWW}$",
    "OpBox": r"$c_{\varphi \Box}$",
    "OpD": r"$c_{\varphi D}$",
    "OWWWtil": r"$c_{\widetilde{WWW}}$",
    "OG": r"$c_G$",
    "OGtil": r"$c_{\widetilde{G}}$",
    "Op": r"$c_{\varphi}$",
    # --------------------------
    # 2L2Q sector
    # --------------------------
    "OQl1M": r"$c_{Ql_1}^{\scriptscriptstyle -}$",
    "OQl2M": r"$c_{Ql_2}^{\scriptscriptstyle -}$",
    "OQl3M": r"$c_{Ql_3}^{\scriptscriptstyle -}$",
    "OQlM": r"$c_{Ql}^{\scriptscriptstyle -}$",
    "Oql1M": r"$c_{ql_1}^{\scriptscriptstyle -}$",
    "Oql2M": r"$c_{ql_2}^{\scriptscriptstyle -}$",
    "Oql3M": r"$c_{ql_3}^{\scriptscriptstyle -}$",
    "OqlM": r"$c_{ql}^{\scriptscriptstyle -}$",
    "OQl13": r"$c_{Ql_1}^{\scriptscriptstyle 3}$",
    "OQl23": r"$c_{Ql_2}^{\scriptscriptstyle 3}$",
    "OQl33": r"$c_{Ql_3}^{\scriptscriptstyle 3}$",
    "OQl3": r"$c_{Ql}^{\scriptscriptstyle 3}$",
    "Oql13": r"$c_{ql_1}^{\scriptscriptstyle 3}$",
    "Oql23": r"$c_{ql_2}^{\scriptscriptstyle 3}$",
    "Oql33": r"$c_{ql_3}^{\scriptscriptstyle 3}$",
    "Oql3": r"$c_{ql}^{\scriptscriptstyle 3}$",
    "OQe": r"$c_{Qe}$",
    "OQmu": r"$c_{Q\mu}$",
    "OQta": r"$c_{Q\tau}$",
    "Oqe": r"$c_{qe}$",
    "Oqmu": r"$c_{q\mu}$",
    "Oqta": r"$c_{q\tau}$",
    "Otl1": r"$c_{tl}^{\scriptscriptstyle 1}$",
    "Otl2": r"$c_{tl}^{\scriptscriptstyle 2}$",
    "Otl3": r"$c_{tl}^{\scriptscriptstyle 3}$",
    "Otl": r"$c_{tl}$",
    "Ote": r"$c_{te}$",
    "Otmu": r"$c_{t\mu}$",
    "Otta": r"$c_{t\tau}$",
    "Oed": r"$c_{ed}$",
    "Omud": r"$c_{\mu d}$",
    "Otad": r"$c_{\tau d}$",
    "Oeb": r"$c_{eb}$",
    "Omub": r"$c_{\mu b}$",
    "Otab": r"$c_{\tau b}$",
    "Oeu": r"$c_{eu}$",
    "Omuu": r"$c_{\mu u}$",
    "Otau": r"$c_{\tau u}$",
    "Ol1d": r"$c_{l_1 d}$",
    "Ol2d": r"$c_{l_2 d}$",
    "Ol3d": r"$c_{l_3 d}$",
    "Ol1b": r"$c_{l_1 b}$",
    "Ol2b": r"$c_{l_2 b}$",
    "Ol3b": r"$c_{l_3 b}$",
    "Ol1u": r"$c_{l_1 u}$",
    "Ol2u": r"$c_{l_2 u}$",
    "Ol3u": r"$c_{l_3 u}$",
    "Olu": r"$c_{l u}$",
    "Old": r"$c_{l d}$",
    "Vud": r"$V_{ud}$",
    "Lprime": r"$L^{\prime (1111)}$",
    "eta1": r"$\eta_1$",
    "eta2": r"$\eta_2$",
    "eta3": r"$\eta_3$",
    "DRV": r"$\Delta_R^V$",
}

group_info_latex = {
    "LEP": r"$\mathrm{LEP}$",
    "LHC": r"$\mathrm{LHC}$",
    "HL-LHC": r"$\mathrm{HL\textrm{-}LHC}$",
    "FCC-ee": r"$\mathrm{FCC\textrm{-}ee}$",
    "Beta decay": r"$\beta\,\mathrm{decay}$",
}
